# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

apikeys: &generic
  recaptcha:
    public_key: 6LcEfRgUAAAAAFPwK7lhq4_r49Q-7tpz-cs2mMZ9
    secret_key: 6LcEfRgUAAAAAFx4mwBZlKmC8mhhc2BfpGCyi4Sx

development:
  <<: *generic
  secret_key_base: c9dd2e10e4ee0e467937eea87675318dbdb3f69829a01d31302373f6c304dc5c2978eb31445b7978cc3d60ebb0f7b3857e07ccba9bbf7fa8dcb830ba19fe1258

test:
  <<: *generic
  secret_key_base: 41b170990b941da7f00db00157c3ebce3c1d5c6c1e676f300290f4021fa579766eeab4cab1abe8c7e3b5e0b2e26c2e9826435a0345c34a46ddcae308037059f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
